### ISSUE TITLE
Error send email

### ISSUE THREAD

**Issue by Sergbmw** [MTry/homebridge-smart-irrigation#10]
Set Email notifications to: Enable
(node:26880) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/homebridge-smart-irrigation'
(node:26880) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

Node.js -  v14.15.4
NPM - v6.14.10

Docker

**Comment by MTry** [comment]
Looks like a permission issue when trying to cache the email enable state - could you check if the same happens when enabling other options? Not able to replicate the same..

**Comment by Sergbmw** [comment]
This only

**Comment by MTry** [comment]
This is indeed strange that it is only showing permission error for email enable - could you try to uninstall and reinstall? Just make sure you save the settings as I understand there are quite a few and you don't want to be entering them again..

**Comment by MTry** [comment]
Did this get solved for you? What changed? Your feedback might throw some light for any other users facing a similar challenge on docker..

**Comment by Sergbmw** [comment]
No, just switched to Pushover
