### ISSUE TITLE
[BUG] Pushover stops sending push notification since the latest update.

### ISSUE THREAD

**Issue by Aekung** [MTry/homebridge-smart-irrigation#17]
**Describe the bug**
Since the latest update that happened few days ago, pushover stops sending smart irrigation system notification. I have rechecked and all the setting is still there in the plugin config. 

**To Reproduce**
Update to the latest version and use Pushover as the way of sending notification.

**Expected behavior**
Pushover should send notification every morning for the watering schedule as it used to.

**Screenshots or logs **
N/A

**Platform (please complete the following information):**
 - Platform: Homebridge
 - Version: 1.3.4

**Additional context**
N/A

**Comment by MTry** [comment]
Haven't received any similar report yet.. and my own system continues to behave as expected. The only thing that changed in the most recent update was nodemailer version and the plugin does not use nodemailer for Pushover notifications- could you recheck your configuration and ensure you have licensed Pushover instance on your device?

**Comment by Aekung** [comment]
> Haven't received any similar report yet.. and my own system continues to behave as expected. The only thing that changed in the most recent update was nodemailer version and the plugin does not use nodemailer for Pushover notifications- could you recheck your configuration and ensure you have licensed Pushover instance on your device?

Really sorry, my bad again. I did change the device-name in pushover backend that day as well and I forgot to update it in the plugin.

Sorry for opening kinda useless support ticket and thanks again for your fast reply.
