### ISSUE TITLE
Not an Issue, but a question ...

### ISSUE THREAD

**Issue by joshimosh** [MTry/homebridge-smart-irrigation#21]
Good morning,
by pure chance I stumbled over your smart irrigation project and I like it. I have a garden and up to now I just start irrigation "by hand", checking if the soil seems to be too dry or not. That is of course not very smart ;-)
The additional proble I am faced with is that because of old pipes the water pressure is poor. So I had to split up into eight different irrigation zones, which I have to irrigate one by one. So I start with zone 1, irrigate for - say 30 minutes -, stop it, then start irrigation on zone 2, run it for - say  25 minutes -  stop it and so on.
How would I achieve this with your smart irrigation ? I have not found a hint to a sequential operation of irrigation of the zones.
Any help in this would be appreciated very much.

Thank you in advance.
Cheers
Martin

**Comment by MTry** [comment]
HI Martin - as a matter of fact the zones only run sequentially! So while that should answer your question, if you were to configure all the 8 zones with the same parameters they would run for the same amount of time one after the other… however you do have a choice to change the variables based on your specific plant groups to make them do what you want.. 30m, 25m so on and so forth! If you configure the number of cycles as more than 1 - say 4, then your zones would get watered one by one 4 times by splitting each discharge time in 4 to give a better chance for soil to absorb water.

Did you get the answer you were looking for?

**Comment by joshimosh** [comment]
Yes, that is exactly what I need, thank you !
And your hint with more than one cycle is great - will do that.
Any hint how to influence the time at which the first of all runs would start ? I have seen a parameter to influence when the last run should end (x minutes before sunrise), but I have no idea when the whole thing will start. Would be nice to influence it, for example for a test run.

Anyway, thanks a lot again for your fast reply.

Cheers
Martin

**Comment by MTry** [comment]
When you restart the plugin after configuring it will tell you the total expected irrigation time - use that as a reference to influence the start time by adjusting the x minutes before sunrise amount. To do a test run in a few minutes, if the plugin is telling you that it will start at 5AM tomorrow morning and right now it is say 7PM in the evening for you - you know that you want to put the parameter x as 10(hours) x 60 = 600 minutes! Maybe use 585 so it will kick in within 15 minutes….

**Comment by joshimosh** [comment]
Ah, ok, I see ...
I have to get used to calculate starting time backwards ;-)
But that's not a big deal. Since there are minimum and maximum irrigation time periods, total minimum and maximum times can be calculated and so I will know earliest and latest start and stop times. It is just different from what I got used to with my static on/off scheme, but I think that I am flexible enough :-)

Thank you for this fine plugin ! 
All the best
Martin

**Comment by MTry** [comment]
Hope your garden blooms better and you get to save water as well :)

Do leave your feedback and a much appreciated star if this works well for you!
