### ISSUE TITLE
Issue With Setup

### ISSUE THREAD

**Issue by nfstange** [MTry/homebridge-smart-irrigation#26]
Hi I am using HOOBS and I added the plugin as I have a water pump hooked up to a smart plug that controls my drip irrigation system. I wanted a sprinkler icon to show me the status when its on. I added your plugin and added it to homekit but the accessory doesn't appear just the bridge any help is appreciated!

**Comment by MTry** [comment]
Hi.. could you update and try with the new version now? v1.6.0

**Comment by MTry** [comment]
I suppose your issue is resolved with the latest update.

**Comment by MTry** [comment]
Hi.. could you share some screenshots? What do you see in the Hoobs accessories?
