### ISSUE TITLE
Using Telegram for Notifications?

### ISSUE THREAD

**Issue by bubffm** [MTry/homebridge-smart-irrigation#3]
This looks like a very interesting plugin to use with my irrigation valves.

One question: I am using Telegram plugin throughout my homebridge to push notifications.  I'd like to stay with that rather than signing up to yet another notification system (Pushcut).

Would it be possible to use your plugin with the telegram service?

Many thanks

**Comment by MTry** [comment]
> This looks like a very interesting plugin to use with my irrigation valves.
> 
> One question: I am using Telegram plugin throughout my homebridge to push notifications. I'd like to stay with that rather than signing up to yet another notification system (Pushcut).
> 

Which telegram plugin are you using?

> Would it be possible to use your plugin with the telegram service?
> 
Will add this to enhancement list 🙂 but at this moment its not. I don't see why it can't be integrated though but will have to check the time it can take me to do so!

**Comment by bubffm** [comment]
Homebridge telegram from grover.   Would be great if that could be done 👍 

https://github.com/grover/homebridge-telegram

**Comment by MTry** [comment]
> Homebridge telegram from grover. Would be great if that could be done 👍
> 
> https://github.com/grover/homebridge-telegram

The plugin you mention.. does it support sending messages for events that occur in HomeKit? - so for now you could always use it and send yourself messages when irrigation starts or finishes by following the state of the irrigation service exposed here - just that those messages will not have any dynamic data from the Irrigation system. 

I know.. not the best option but you will know when watering started and ended!

**Comment by bubffm** [comment]
>>The plugin you mention.. does it support sending messages for events that occur in HomeKit? 

Yes it does.  I'll play around with it.  Thanks.

**Comment by bubffm** [comment]
One other thing I noticed:  On "real" valves, I get a countdown timer next to the waterdrop symbol in EVE.  
On the "dummy" I get the moving waterdops in EVE but no counter next to it.  Is this intentional?

**Comment by MTry** [comment]
On the contrary.. there is a countdown timer at the valve as well as the service levels! Is this what you observe in the Home app as well!? I am unable to reproduce this as I do see these remaining duration timers!

**Comment by MTry** [comment]
Have added this to the way forward items..
