### ISSUE TITLE
Docker related - Standing reboot - Fixed v1.7.1

### ISSUE THREAD

**Issue by Sergbmw** [MTry/homebridge-smart-irrigation#30]
**Describe the bug**
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/homebridge-smart-irrigation'

reboot standing

**Platform (please complete the following information):**
ОС | Ubuntu Bionic Beaver (18.04.6 LTS)
raspberrypi
v16.14.2
v8.5.5
root
/homebridge
/homebridge/config.json
/homebridge/node_modules
docker: Yes

**Additional context**

**Comment by MTry** [comment]
Hi @Sergbmw - could you clarify that the problem you are facing of continuous reboots? This is looking like some permission issue on your docker installation. Any other plugins you have installed and is the behaviour normal otherwise?

**Comment by Sergbmw** [comment]
All other plugins work great

**Comment by MTry** [comment]
TBH I haven't tried an installation of homebridge on docker so not quite sure where this permission denial to 'mkdir' is coming from - any chance you can try on non-docker environment? The way it looks form your error message - am I correct in assuming that you are not able to install the plugin itself? Or is it that the plugin installs and you are able to configure but when you start it keeps rebooting? I am also assuming that since the installation itself is not proceeding there is no point asking if the plugin is on a child bridge!?

**Comment by MTry** [comment]
@Sergbmw - could you tell me how you are trying to install? Through the UI or install command? Any other feedback on the previous message?

**Comment by Sergbmw** [comment]
Good afternoon. I installed the plugin and configured it. But after reloading the Homebridge, if the plugin is not started in a separate bridge, the Homebridge itself does not start.

**Comment by Sergbmw** [comment]
I already completely uninstalled the plugin and reinstalled it, the same problem

**Comment by MTry** [comment]
So if you start in a child bridge then homebridge starts but the plugin doesn’t? Isn’t it required to first configure and restart to even get the option to make it a child bridge? - so if homebrdige didn’t start after reboot could you share how you forced the plugin to run in child bridge mode?

**Comment by Sergbmw** [comment]
Tried it in different ways, same result.

**Comment by MTry** [comment]
How did you make the plugin run in child bridge?

**Comment by MTry** [comment]
Thanks - do you do this from this screen right after installation just after configuring or do you try to restart the home bridge after the plugin installation and return to this screen to make it a child bridge...

**Comment by Sergbmw** [comment]
[4/4/2022, 11:48:46 AM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 49FD) is running on port 52434.
[4/4/2022, 11:48:46 AM] [Irrigation] Exposing controls to Homekit...
[4/4/2022, 11:48:46 AM] [Irrigation] Exposed Master Control
[4/4/2022, 11:48:46 AM] [Irrigation] Initialized 1 zones
DEPRECATED user supplied a custom 'mdns' option. This option is deprecated and ignored. Please move to the new 'bind' option.
[4/4/2022, 11:48:46 AM] [Irrigation] Check configuration errors. Currently disabled!
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/homebridge-smart-irrigation'
[4/4/2022, 11:48:46 AM] [Irrigation] Child bridge process ended
[4/4/2022, 11:48:46 AM] [Irrigation] Process Ended. Code: 1, Signal: null

**Comment by Sergbmw** [comment]
[4/4/2022, 11:49:42 AM] [Irrigation] OWM Key cant be blank! Disabling
[4/4/2022, 11:49:42 AM] [Irrigation] Exposing controls to Homekit...
[4/4/2022, 11:49:42 AM] [Irrigation] Exposed Master Control
[4/4/2022, 11:49:42 AM] [Irrigation] Initialized 1 zones
[4/4/2022, 11:49:42 AM] [Irrigation] Check configuration errors. Currently disabled!
DEPRECATED user supplied a custom 'mdns' option. This option is deprecated and ignored. Please move to the new 'bind' option.
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/homebridge-smart-irrigation'
[4/4/2022, 11:49:42 AM] [Irrigation] Child bridge process ended
[4/4/2022, 11:49:42 AM] [Irrigation] Process Ended. Code: 1, Signal: null
[4/4/2022, 11:49:49 AM] [Irrigation] Restarting Process...
[4/4/2022, 11:49:50 AM] [Irrigation] Launched child bridge with PID 9487
[4/4/2022, 11:49:51 AM] Registering accessory 'homebridge-smart-irrigation.SmartSprinklers'
[4/4/2022, 11:49:51 AM] [Irrigation] Loaded homebridge-smart-irrigation v1.6.0 child bridge successfully
[4/4/2022, 11:49:51 AM] [Irrigation] OWM Key cant be blank! Disabling
[4/4/2022, 11:49:51 AM] [Irrigation] Exposing controls to Homekit...
[4/4/2022, 11:49:51 AM] [Irrigation] Exposed Master Control
[4/4/2022, 11:49:51 AM] [Irrigation] Initialized 1 zones
[4/4/2022, 11:49:51 AM] [Irrigation] Check configuration errors. Currently disabled!
DEPRECATED user supplied a custom 'mdns' option. This option is deprecated and ignored. Please move to the new 'bind' option.
Error: EACCES: permission denied, mkdir '/run/s6/services/homebridge-config-ui-x/homebridge-smart-irrigation'
[4/4/2022, 11:49:51 AM] [Irrigation] Child bridge process ended
[4/4/2022, 11:49:51 AM] [Irrigation] Process Ended. Code: 1, Signal: null

**Comment by MTry** [comment]
Thanks for the logs - it is looking like, from the stage at which the error is thrown, that the plugin is unable to get permission for the local subdirectory where it needs to store some temp files for persistence… unfortunately I don’t have a docker environment nor the expertise for the same to guide you here but my suggestion would be to dig in that direction.. you could start by loosening permissions at the plugin’s installation sub-directory and check if it makes a difference.. or even just create a /homebridge-smart-irrigation/storage subdirectory with read/write permissions to check if it helps!

Please do give a feedback that could help others here..

**Comment by Sergbmw** [comment]
Yes, other plugins have full access, and I run it in a docker Homebridge under the administrator, in theory, I have all access

**Comment by OzBMP** [comment]
Hi Sergbmw, 

Did you have any luck here? I have the exact same issue and also using docker on Synology nas.

**Comment by seppelicous** [comment]
> 

Also using Docker on Synology with DSM 7.1 and having the same issue! Had to disable the plugin.

**Comment by seppelicous** [comment]
The root of the issue is, that "'/run/s6/services/*" is not the correct directory for temp files in docker. As there is no individual option for the user to change the folder, it is up to the author to provide the correct setting.

Thank you!

**Comment by MTry** [comment]
> 

@seppelicous - I'm not an expert when it comes to doing this on the docker but welcome any code updates you think will fix this without breaking non-docker implementation. Happy to incorporate this change but will can't do on my own unfortunately. Requesting expert assistance with this... until then will keep this issue open.

**Comment by seppelicous** [comment]
@MTry Thank you for the fast reply. I understand your worries. Some plugin authors add and additional option to individualy change the cached directory. Maybe this would be an option here.

**Comment by MTry** [comment]
Ok.. let me look into this. In the meanwhile if you have a specific suggestion looking at the code please do share as that will make it quicker to implement this..

**Comment by MTry** [comment]
@seppelicous - I am using `const cacheDirectory = './homebridge-smart-irrigation/storage'` as temp storage.. what according to you would be suitable for docker? Would you like to fork and experiment with a different value here? If it works for you I'll make this setting a part of configuration to give the user an option to pick the right one..

**Comment by MTry** [comment]
Edited the title to better reflect the issue here. Still waiting for some guidance on this from docker experts..

**Comment by seppelicous** [comment]
Sorry for answering so late!

I checked another discussion with the same issue: https://github.com/benzman81/homebridge-nukiio/issues/27
It seems that the valid cached directory needs to be within "/homebridge". Does your plugin creates a folder while installation?

For a first try it would be fine to an additional setting in the configuration. I will test is immediately

**Comment by MTry** [comment]
> All Work!

Super. Thanks for your super fast feedback!! Will wait a little longer before marking it closed.. perhaps some more user feedback!

**Comment by MTry** [comment]
Made a minor update.. so users on platforms where it was earlier working without issues, should not have to reset the control states in Home for their preferences... 

Hope this is the last change for this issue and it works for you all!

Thank you so much for your patience and for highlighting this issue which was squarely due to my own error of not following a basic guideline - apologies for the same!

**Comment by seppelicous** [comment]
Works also for me! Thank you very much for this! Great job!

**Comment by MTry** [comment]
@seppelicous Thanks for your feedback!
