### ISSUE TITLE
Help or Questions

### ISSUE THREAD

**Issue by matbe81** [MTry/homebridge-smart-irrigation#31]
Hi,

Just wondering:
- is it normal I receive pushover notification every 2 minutes days and night? - see attach. How to limit that to only get that when relevant information like once a day on the forecast planning + when irrigation start and stop.

![image](https://user-images.githubusercontent.com/8006424/162124686-a62dcaa4-3946-4cc3-afac-132709a39db9.png)

- I dont received email notification despite correct configuration in that sense?

- Do I currently setup the irrigation trigger? (See picture)
![image](https://user-images.githubusercontent.com/8006424/162125148-31c019ea-aa25-4458-8ad4-69dd506b5cce.png)

**Comment by MTry** [comment]
Hi,

Not normal at all! It will only send the notification on reassessment and from the screenshot you shared it clearly states that it is set for the next day.. so the only thing that will force a recalculation is a restart of the plugin or reboot. On every reboot/restart as the plugin loads it will send out a notification. Can you check the logs and confirm this is what is causing this?
What mail server are you using? - could you check the logs if they reveal more?

**Comment by matbe81** [comment]
I see one error related to email notification:
[4/7/2022, 8:30:22 AM] [Irrigation] Email enabled but configuration items cant be blank! Disabling Email

Strange as configuration look clear.

Can I sent you the logs § configuration in a private email (as it can contains sensitive information)?

**Comment by MTry** [comment]
I don't see the smtp user and password settings in your config!

` "userID": "XXX@yyyyy.com",
  "userPwd": "qwerytlkjasfj",`

Those are the blank items the plugin seems to be complaining about..  try fixing that and let me know if it works. Are you on discord by any chance?


> I see one error related to email notification: [4/7/2022, 8:30:22 AM] [Irrigation] Email enabled but configuration items cant be blank! Disabling Email
> 
> Strange as email notification were working some months ago (before winter). I don't have values in username & passwod for smtp as the server didn't require authentication.
> 
> Strange as configuration look clear (I have anonymized sensitive values): `{ "accessory": "SmartSprinklers", "name": "Irrigation", "verbosed": true, "masterDisable": false, "exposeControls": true, "recheckTime": 15, "latitude": 1, "longitude": 1, "altitude": 104, "keyAPI": "xxx", "cycles": 2, "sunriseOffset": 20, "lowThreshold": 5, "highThreshold": 10, "emailEnable": true, "senderName": "Irrigation Control", "senderEmail": "irrigation@xxx.net", "sendTo": "mg@xxx.be", "smtpHost": "smtp.voo.be", "smtpPort": 25, "portSecure": false, "pushEnable": true, "userPO": "xxx", "tokenPO": "xxx", "devicePO": "MatiPhone", "priorityPO": 0, "soundPO": "pushover", "pcEnable": false, "pcWeatherCheckedSound": "system", "pcWateringStartSound": "system", "pcWateringEndSound": "jobDone", "JanRad": 0.9, "FebRad": 1.7, "MarRad": 3, "AprRad": 4.6, "MayRad": 5.7, "JunRad": 6.3, "JulRad": 6.2, "AugRad": 5.3, "SepRad": 3.8, "OctRad": 2.2, "NovRad": 1.1, "DecRad": 0.7, "zones": [ { "zoneName": "Jardin avant", "enabled": true, "adaptive": true, "rainFactoring": true, "defDuration": 10, "maxDuration": 30, "rainThreshold": 2.5, "tweakFactor": 100, "dripLPH": 2, "dripNos": 21, "dripArea": 20, "efficiency": 90, "cropCoef": 0.5, "plantDensity": 1, "expFactor": 0.5, "wateringMonths": [ "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct" ], "wateringWeekdays": [ "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" ] } ] }`
> 
> Can I sent you the logs in a private email (as it can contains sensitive information)?

**Comment by matbe81** [comment]
I don't have values in username & password for smtp as the server didn't require authentication.

I'm on Discord: Mat#2860

**Comment by MTry** [comment]
> I don't have values in username & password for smtp as the server didn't require authentication.
> 
> I'm on Discord: Mat#2860

That's a risky place to be in though I shouldn't be judging 😳 - never thought of a use case where there would be no authentication for using an SMTP and that's the reason for this validation being there! But it does confirm the root of your problem with email through the plugin - could I nudge you to create a basic authentication for the smtp server you are using and try this? I really feel uncomfortable removing the validation for the plugin itself.

**Comment by MTry** [comment]
Did you solve the problem of push notifications every other minute? What was the cause?

**Comment by matbe81** [comment]
In reality, authentication is not a requirement for SMTP server (https://en.wikipedia.org/wiki/SMTP_Authentication). There is a lot of ISP in Europe that provide open SMTP for their customers. They whitelist only people passing by their network as an authentication alternative.

So I advice you to made this field optional and to issue an error in log where authentication issue occurs.

In my case, I filled in any value in both username and password fields and it works, but could not work for some ISP who required NO authentication at all and will reject any username or password. So not very clean on my point of view.

Now, I receive Pushover + email notification every ~8-9 minutes.

**Comment by MTry** [comment]
You have point there.. perhaps in the next version bump.
Regarding the recurring messages - could you check the homebridge logs or share them to investigate what could be causing them?

**Comment by matbe81** [comment]
Thank you for understanding my point of view.

Please find the logs here:

`[homebridge.log.txt](https://github.com/MTry/homebridge-smart-irrigation/files/8440829/homebridge.log.txt)`

**Comment by matbe81** [comment]
Thank you for understanding my point of view.

How can I send you the logs securely?

**Comment by MTry** [comment]
@matbe81 - as we discussed its possibly another plugin creating the instability - hope you solved the issue now? If not do reopen this issue..
