### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by patyi40** [MTry/homebridge-smart-irrigation#33]
Hi,

I use Hoobs v 4.0.110 and installed this plugin. Looks like this is exactly what I looking for. I configured it but after restart I saw in log the next message:

Error loading plugin "homebridge-smart-irrigation"

I tried reinstall it but I have same issue.

Can you help me, please?

**Comment by MTry** [comment]
Hi - did you configure it? Can you share the settings and any other messages shared by the plugin?

When sharing settings please MASK OUT any email userIDs/PWDs before posting….

**Comment by patyi40** [comment]
Hi,

Thanks for quick reply.

"accessories": [
        {
            "accessory": "SmartSprinklers",
            "name": "Irrigation",
            "verbosed": true,
            "masterDisable": true,
            "exposeControls": true,
            "latitude": 46.3598087,
            "longitude": 17.7321198,
            "altitude": 124,
            "keyAPI": "my-key-mask",
            "cycles": 1,
            "sunriseOffset": 0,
            "lowThreshold": 5,
            "highThreshold": 10,
            "senderName": "💦 Irrigation Control",
            "smtpPort": 587,
            "JanRad": 6,
            "FebRad": 6,
            "MarRad": 6,
            "AprRad": 6,
            "MayRad": 6,
            "JunRad": 6,
            "JulRad": 6,
            "AugRad": 6,
            "SepRad": 6,
            "OctRad": 6,
            "NovRad": 6,
            "DecRad": 6,
            "zones": [
                {
                    "defDuration": 20,
                    "maxDuration": 30,
                    "rainThreshold": 2.5,
                    "tweakFactor": 100,
                    "dripLPH": 2,
                    "dripNos": 1,
                    "dripArea": 1,
                    "efficiency": 90,
                    "cropCoef": 0.5,
                    "plantDensity": 1,
                    "expFactor": 1,
                    "wateringMonths": [
                        "Apr, May, Jun, Jul, Aug, Sep"
                    ],
                    "wateringWeekdays": [
                        "Monday, Tuesday, wednesday, Thursday, Friday, Saturday, Sunday"
                    ],
                    "zoneName": "Main",
                    "enabled": true,
                    "adaptive": true,
                    "rainFactoring": true
                }
            ],
            "plugin_map": {
                "plugin_name": "homebridge-smart-irrigation"
            },
            "senderEmail": "email",
            "sendTo": "email",
            "smtpHost": "smtp.mail.me.com",
            "userID": "email",
            "userPwd": "password",
            "portSecure": true,
            "emailEnable": true
        }
    ]
}

**Comment by MTry** [comment]
Could you also share the detail log? What platform do you use? Although I don’t use/verify on Hoobs I might be able to take a look and suggest possibilities..

**Comment by patyi40** [comment]
2022. 04. 17. 11:52:34homebridge starting
2022. 04. 17. 11:52:36homebridgeInitializing HAP-NodeJS v0.9.4...
2022. 04. 17. 11:52:37homebridgeLoaded plugin 'homebridge-camera-ffmpeg'
2022. 04. 17. 11:52:37homebridgeRegistering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
2022. 04. 17. 11:52:37homebridgeLoaded plugin 'homebridge-harmony'
2022. 04. 17. 11:52:37homebridgeRegistering platform 'homebridge-harmony.HarmonyHubWebSocket'
2022. 04. 17. 11:52:37homebridgeERRORError loading plugin "homebridge-smart-irrigation"
2022. 04. 17. 11:52:38homebridgeLoaded plugin 'homebridge-unifi-protect'
2022. 04. 17. 11:52:38homebridgeRegistering platform 'homebridge-unifi-protect.UniFi Protect'
2022. 04. 17. 11:52:38homebridgeLoading 3 platforms...
2022. 04. 17. 11:52:38homebridgeHarmonyHubHarmonyPlatform Init
2022. 04. 17. 11:52:38homebridgeLoading 1 accessories...
2022. 04. 17. 11:52:38homebridgeHarmonyHubDidFinishLaunching
2022. 04. 17. 11:52:38homebridgeHarmonyHub(HarmonyHub)INFO - Loading activities...
2022. 04. 17. 11:52:38homebridgePreparing Advertiser for 'homebridge 9B7F' using bonjour-hap backend!
2022. 04. 17. 11:52:38homebridgeStarting to advertise 'homebridge 9B7F' using bonjour-hap backend!
2022. 04. 17. 11:52:38homebridgeBridge is running on port 51826.
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Adding Accessory : HarmonyHub-TV
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - configuring Main TV Service
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating TV Service
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating Input Service - Watch TV 2 in position 1
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating Input Service - Listen to Music in position 2
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating Input Service - Watch TV in position 3
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating Input Service - RTL KLUB nappali in position 4
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)WARNING - No main Activity that match config file found, default to first one
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Configuring Main Activity Watch TV 2
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating TV Speaker Service
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Discovered Activity : Watch TV 2
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Discovered Activity : Listen to Music
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Discovered Activity : Watch TV
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Discovered Activity : RTL KLUB nappali
2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - setupFoundAccessories - TV accessory added as external accessory
2022. 04. 17. 11:52:39homebridgePreparing Advertiser for 'HarmonyHub-TV 435F' using bonjour-hap backend!
2022. 04. 17. 11:52:39homebridgeStarting to advertise 'HarmonyHub-TV 435F' using bonjour-hap backend!
2022. 04. 17. 11:52:39homebridgeHarmonyHub-TV 435F is running on port 34743.
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Connected to the UniFi Protect controller API (address: 192.168.1.78 mac: B4FBE4D3C091).
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Connected to the UniFi Protect realtime update events API.
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Garázs [UVC G3] (address: 192.168.1.82 mac: FCECDA3094E3).
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Bejárat [UVC G3] (address: 192.168.1.85 mac: FCECDAD863C2).
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Előkert [UVC G3] (address: 192.168.1.70 mac: FCECDA30938A).
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Terasz [UVC G3] (address: 192.168.1.67 mac: FCECDA309389).
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Dolgozó [UVC G3] (address: 192.168.1.84 mac: FCECDAD85D9B).
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Kert [UVC G3] (address: 192.168.1.66 mac: FCECDAD85ED9).
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Controller refresh interval set to 10 seconds.
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Garázs [UVC G3]: HomeKit Secure Video support enabled.
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Bejárat [UVC G3]: HomeKit Secure Video support enabled.
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Előkert [UVC G3]: HomeKit Secure Video support enabled.
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Terasz [UVC G3]: HomeKit Secure Video support enabled.
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Dolgozó [UVC G3]: HomeKit Secure Video support enabled.
2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Kert [UVC G3]: HomeKit Secure Video support enabled.

**Comment by angyalz** [comment]
> 2022. 04. 17. 11:52:34homebridge starting
> 
> 2022. 04. 17. 11:52:36homebridgeInitializing HAP-NodeJS v0.9.4...
> 
> 2022. 04. 17. 11:52:37homebridgeLoaded plugin 'homebridge-camera-ffmpeg'
> 
> 2022. 04. 17. 11:52:37homebridgeRegistering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
> 
> 2022. 04. 17. 11:52:37homebridgeLoaded plugin 'homebridge-harmony'
> 
> 2022. 04. 17. 11:52:37homebridgeRegistering platform 'homebridge-harmony.HarmonyHubWebSocket'
> 
> 2022. 04. 17. 11:52:37homebridgeERRORError loading plugin "homebridge-smart-irrigation"
> 
> 2022. 04. 17. 11:52:38homebridgeLoaded plugin 'homebridge-unifi-protect'
> 
> 2022. 04. 17. 11:52:38homebridgeRegistering platform 'homebridge-unifi-protect.UniFi Protect'
> 
> 2022. 04. 17. 11:52:38homebridgeLoading 3 platforms...
> 
> 2022. 04. 17. 11:52:38homebridgeHarmonyHubHarmonyPlatform Init
> 
> 2022. 04. 17. 11:52:38homebridgeLoading 1 accessories...
> 
> 2022. 04. 17. 11:52:38homebridgeHarmonyHubDidFinishLaunching
> 
> 2022. 04. 17. 11:52:38homebridgeHarmonyHub(HarmonyHub)INFO - Loading activities...
> 
> 2022. 04. 17. 11:52:38homebridgePreparing Advertiser for 'homebridge 9B7F' using bonjour-hap backend!
> 
> 2022. 04. 17. 11:52:38homebridgeStarting to advertise 'homebridge 9B7F' using bonjour-hap backend!
> 
> 2022. 04. 17. 11:52:38homebridgeBridge is running on port 51826.
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Adding Accessory : HarmonyHub-TV
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - configuring Main TV Service
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating TV Service
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating Input Service - Watch TV 2 in position 1
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating Input Service - Listen to Music in position 2
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating Input Service - Watch TV in position 3
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating Input Service - RTL KLUB nappali in position 4
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)WARNING - No main Activity that match config file found, default to first one
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Configuring Main Activity Watch TV 2
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Creating TV Speaker Service
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Discovered Activity : Watch TV 2
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Discovered Activity : Listen to Music
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Discovered Activity : Watch TV
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - Discovered Activity : RTL KLUB nappali
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub(HarmonyHub)INFO - setupFoundAccessories - TV accessory added as external accessory
> 
> 2022. 04. 17. 11:52:39homebridgePreparing Advertiser for 'HarmonyHub-TV 435F' using bonjour-hap backend!
> 
> 2022. 04. 17. 11:52:39homebridgeStarting to advertise 'HarmonyHub-TV 435F' using bonjour-hap backend!
> 
> 2022. 04. 17. 11:52:39homebridgeHarmonyHub-TV 435F is running on port 34743.
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Connected to the UniFi Protect controller API (address: 192.168.1.78 mac: B4FBE4D3C091).
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Connected to the UniFi Protect realtime update events API.
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Garázs [UVC G3] (address: 192.168.1.82 mac: FCECDA3094E3).
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Bejárat [UVC G3] (address: 192.168.1.85 mac: FCECDAD863C2).
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Előkert [UVC G3] (address: 192.168.1.70 mac: FCECDA30938A).
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Terasz [UVC G3] (address: 192.168.1.67 mac: FCECDA309389).
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Dolgozó [UVC G3] (address: 192.168.1.84 mac: FCECDAD85D9B).
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Discovered camera: Kert [UVC G3] (address: 192.168.1.66 mac: FCECDAD85ED9).
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS]: Controller refresh interval set to 10 seconds.
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Garázs [UVC G3]: HomeKit Secure Video support enabled.
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Bejárat [UVC G3]: HomeKit Secure Video support enabled.
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Előkert [UVC G3]: HomeKit Secure Video support enabled.
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Terasz [UVC G3]: HomeKit Secure Video support enabled.
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Dolgozó [UVC G3]: HomeKit Secure Video support enabled.
> 
> 2022. 04. 17. 11:52:40homebridgeUniFi ProtectUniFi-CloudKey-Gen2-Plus [UCK-G2-PLUS] Kert [UVC G3]: HomeKit Secure Video support enabled.
> 
> 

Could you run Hoobs in debug mode? This log hasn't enough info.

**Comment by patyi40** [comment]
I think so Hoobs in debug mode.

2022. 04. 17. 16:12:46homebridge starting
2022. 04. 17. 16:12:48homebridgeInitializing HAP-NodeJS v0.9.4...
2022. 04. 17. 16:12:49homebridgeLoaded plugin 'homebridge-camera-ffmpeg'
2022. 04. 17. 16:12:49homebridgeRegistering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
2022. 04. 17. 16:12:49homebridgeLoaded plugin 'homebridge-harmony'
2022. 04. 17. 16:12:49homebridgeRegistering platform 'homebridge-harmony.HarmonyHubWebSocket'
2022. 04. 17. 16:12:49homebridgeERRORError loading plugin "homebridge-smart-irrigation"
2022. 04. 17. 16:12:49homebridgeLoaded plugin 'homebridge-unifi-protect'
2022. 04. 17. 16:12:49homebridgeRegistering platform 'homebridge-unifi-protect.UniFi Protect'
2022. 04. 17. 16:12:49homebridgeLoading 3 platforms...
2022. 04. 17. 16:12:49homebridgeHarmonyHubHarmonyPlatform Init
2022. 04. 17. 16:12:49homebridgeLoading 1 accessories...
2022. 04. 17. 16:12:49homebridgeHarmonyHubDidFinishLaunching
2022. 04. 17. 16:12:49homebridgeHarmonyHub(HarmonyHub)INFO - Loading activities...
2022. 04. 17. 16:12:50homebridgePreparing Advertiser for 'homebridge A91D' using bonjour-hap backend!
2022. 04. 17. 16:12:50homebridgeStarting to advertise 'homebridge A91D' using bonjour-hap backend!
2022. 04. 17. 16:12:50homebridgeBridge is running on port 51826.

UI: Szia Zoltán! A helyszín Kaposújlak, telepített öntözőfejekkel.

**Comment by angyalz** [comment]
Well, I think we need verbose mode (-v or --verbose) log

**Comment by patyi40** [comment]
I typed next command in terminal for verbose mode:

hoobs@hoobs:~ $ sudo hoobsd hub -v
[sudo] password for hoobs: 
Initializing HAP-NodeJS v0.9.4...
4.0.110
hoobs@hoobs:~ $ 

I hope Hoobs is in verbose mode now.

After restarted Hoobs and copied from Log:

2022. 04. 17. 17:14:36homebridge starting
2022. 04. 17. 17:14:36homebridge starting
2022. 04. 17. 17:14:38homebridgeInitializing HAP-NodeJS v0.9.4...
2022. 04. 17. 17:14:38homebridgeInitializing HAP-NodeJS v0.9.4...
2022. 04. 17. 17:14:39homebridgeLoaded plugin 'homebridge-camera-ffmpeg'
2022. 04. 17. 17:14:39homebridgeLoaded plugin 'homebridge-camera-ffmpeg'
2022. 04. 17. 17:14:39homebridgeRegistering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
2022. 04. 17. 17:14:39homebridgeRegistering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
2022. 04. 17. 17:14:39homebridgeLoaded plugin 'homebridge-harmony'
2022. 04. 17. 17:14:39homebridgeLoaded plugin 'homebridge-harmony'
2022. 04. 17. 17:14:39homebridgeRegistering platform 'homebridge-harmony.HarmonyHubWebSocket'
2022. 04. 17. 17:14:39homebridgeRegistering platform 'homebridge-harmony.HarmonyHubWebSocket'
2022. 04. 17. 17:14:39homebridgeERRORError loading plugin "homebridge-smart-irrigation"
2022. 04. 17. 17:14:39homebridgeERRORError loading plugin "homebridge-smart-irrigation"
2022. 04. 17. 17:14:40homebridgeLoaded plugin 'homebridge-unifi-protect'
2022. 04. 17. 17:14:40homebridgeLoaded plugin 'homebridge-unifi-protect'
2022. 04. 17. 17:14:40homebridgeRegistering platform 'homebridge-unifi-protect.UniFi Protect'
2022. 04. 17. 17:14:40homebridgeRegistering platform 'homebridge-unifi-protect.UniFi Protect'
2022. 04. 17. 17:14:40homebridgeLoading 3 platforms...
2022. 04. 17. 17:14:40homebridgeLoading 3 platforms...
...

**Comment by angyalz** [comment]
I haven't Hoobs, but a tip: sudo hoobsd hub -d -v

**Comment by angyalz** [comment]
Or I just now found it: sudo hbs log -d. 
Maybe it helps understand the cause of the error.

**Comment by MTry** [comment]
@patyi40 - any luck with the verbose log?

**Comment by patyi40** [comment]
Good Morning guys,

I have a good news, irrigation plugin loaded without issue. This is my fault, exactly it is issue of Hoobs because it used Homebridge 1.3.4 after Hoobs update. I found an article how can I fix:
https://github.com/hoobs-org/HOOBS/issues/1760
After repair Hoobs I installed Smart Irrigation plugin and voila:

homebridge starting
2022. 04. 23. 9:44:12homebridgeLoaded plugin 'homebridge-camera-ffmpeg'
2022. 04. 23. 9:44:12homebridgeLoaded plugin 'homebridge-harmony'
2022. 04. 23. 9:44:12homebridgeLoaded plugin 'homebridge-samsungtvht'
2022. 04. 23. 9:44:12homebridgeLoaded plugin 'homebridge-smart-irrigation'
2022. 04. 23. 9:44:13homebridgeLoaded plugin 'homebridge-unifi-protect'
2022. 04. 23. 9:44:13homebridgeLoading 4 platforms...
2022. 04. 23. 9:44:13homebridgeHarmonyHubHarmonyPlatform Init
2022. 04. 23. 9:44:13homebridgeLoading 1 accessories...
2022. 04. 23. 9:44:13homebridgeIrrigationExposing controls to Homekit...
2022. 04. 23. 9:44:13homebridgeIrrigationExposed Master Control
2022. 04. 23. 9:44:13homebridgeIrrigationInitialized 1 zones
2022. 04. 23. 9:44:13homebridgeHarmonyHubDidFinishLaunching
2022. 04. 23. 9:44:13homebridgeHarmonyHub(HarmonyHub)INFO - Loading activities...
2022. 04. 23. 9:44:13homebridgeHarmonyHub(HarmonyHub)INFO - Loading activities...
2022. 04. 23. 9:44:13homebridgeSamsung TV HTLoading device 1: TV 192.168.1.101
2022. 04. 23. 9:44:13homebridgeSamsung TV HTLoading device 2: Samsung TV 40 192.168.1.147
2022. 04. 23. 9:44:14homebridgeTV 2147 is running on port 41659.
2022. 04. 23. 9:44:14homebridgeSamsung TV 40 DE82 is running on port 41263.
2022. 04. 23. 9:44:14homebridgeBridge is running on port 51826.
2022. 04. 23. 9:44:14homebridgeIrrigationEnabling irrigation. Will also recalculate now...
2022. 04. 23. 9:44:14homebridgeIrrigation-----------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationlight rain on Saturday 4/23/2022 with 96% clouds & 79% RH
2022. 04. 23. 9:44:14homebridgeIrrigationETo:2.86mm|Rain:0.35mm|Min:8.54°C|Max:16.25°C|Wind:4.27m/s
2022. 04. 23. 9:44:14homebridgeIrrigation-----------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationscattered clouds on Sunday 4/24/2022 with 44% clouds & 52% RH
2022. 04. 23. 9:44:14homebridgeIrrigationETo:5.14mm|Rain:0mm|Min:8.99°C|Max:20.22°C|Wind:8.91m/s
2022. 04. 23. 9:44:14homebridgeIrrigation-----------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationlight rain on Monday 4/25/2022 with 63% clouds & 59% RH
2022. 04. 23. 9:44:14homebridgeIrrigationETo:3.54mm|Rain:0.27mm|Min:7.71°C|Max:16.24°C|Wind:3.86m/s
2022. 04. 23. 9:44:14homebridgeIrrigation-----------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationlight rain on Tuesday 4/26/2022 with 76% clouds & 74% RH
2022. 04. 23. 9:44:14homebridgeIrrigationETo:2.92mm|Rain:1.13mm|Min:8.91°C|Max:14.17°C|Wind:3.34m/s
2022. 04. 23. 9:44:14homebridgeIrrigation-----------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationlight rain on Wednesday 4/27/2022 with 100% clouds & 78% RH
2022. 04. 23. 9:44:14homebridgeIrrigationETo:2.96mm|Rain:1.95mm|Min:10.34°C|Max:15.85°C|Wind:2.3m/s
2022. 04. 23. 9:44:14homebridgeIrrigation-----------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationbroken clouds on Thursday 4/28/2022 with 64% clouds & 51% RH
2022. 04. 23. 9:44:14homebridgeIrrigationETo:3.92mm|Rain:0mm|Min:10.09°C|Max:17.32°C|Wind:3.3m/s
2022. 04. 23. 9:44:14homebridgeIrrigation-----------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationfew clouds on Friday 4/29/2022 with 13% clouds & 48% RH
2022. 04. 23. 9:44:14homebridgeIrrigationETo:3.86mm|Rain:0mm|Min:9.67°C|Max:17°C|Wind:2.9m/s
2022. 04. 23. 9:44:14homebridgeIrrigation-----------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationfew clouds on Saturday 4/30/2022 with 14% clouds & 46% RH
2022. 04. 23. 9:44:14homebridgeIrrigationETo:3.70mm|Rain:0mm|Min:9.01°C|Max:18.56°C|Wind:1.99m/s
2022. 04. 23. 9:44:14homebridgeIrrigation------------------------------------------------
2022. 04. 23. 9:44:14homebridgeIrrigationNo schedule set:
2022. 04. 23. 9:44:14homebridgeIrrigation-No schedule available or no watering needed
2022. 04. 23. 9:44:14homebridgeIrrigationRecalculation set for: 4/24/2022, 5:46:42 AM
...

So, Smart Irrigation plugin doesn't have bug, it works great.
I will test it and share with you my experience.

Thank you so much for your support and help! 
Have a nice day!

**Comment by MTry** [comment]
Thank you for your feedback and posting your experience for others' benefit!
