### ISSUE TITLE
Choosing hour of irrigation

### ISSUE THREAD

**Issue by matbe81** [MTry/homebridge-smart-irrigation#39]
Hi,

I read some scientist documentation recommending to irrigate at evening in place of morning.

- What do you think?
- How to choose that in the Smart Irrigation plugin?

Thank you !

**Comment by MTry** [comment]
The choice is yours as there are multiple opinions on this. The way to achieve it would be to give a negative number in sunriseoffset: so a -60 in the setting will result in irrigation being concluded by 1 hour post sunrise. Calculate for your evening in terms of the number of minutes post sunrise.

**Comment by matbe81** [comment]
Thank you. 

Is it possible to define a timing related to sunset in place of sunrise as length of days can very a lot depending of the month?

**Comment by MTry** [comment]
Sorry.. that's not possible at the moment or planned 🙂

I do understand your point though but it would take quite a bit of code update to do this..
