### ISSUE TITLE
Integration of FakeGato

### ISSUE THREAD

**Issue by miquellaboria** [MTry/homebridge-smart-irrigation#6]
Will be a good feature integrate with FakeGato:
https://github.com/simont77/fakegato-history

**Comment by MTry** [comment]
> Will be a good feature integrate with FakeGato:
> https://github.com/simont77/fakegato-history

Hi Miquel - what exactly would you like to see in the history?

**Comment by miquellaboria** [comment]
The water consumition ;)

`this.LoggingService.addEntry({ time: Math.round(new Date().valueOf() / 1000), status: this.power, waterAmount: this.waterAmount });`

**Comment by MTry** [comment]
Will try to get this done.. added to the to-do list
