### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by leandromagro** [MTry/homebridge-smart-irrigation#7]
Hi @MTry 
Didn’t figure out how to setup my water valve (sprinkler) to work with the sprinklers created for each zone.
Could you give me a hint?
(I’m using Eve, HomeKit Controller or the default app).
Thanks!

**Comment by subcritical71** [comment]
Did you get this figured out? I used Eve and for each zone I created two scenes. One to turn on the physical Zone and one to turn off the physical zone. Then I created two rules per zone. One to sense when the dummy zone changes to on (which calls the On scene), and one to sense the zone to off (which calls the Off scene).

**Comment by MTry** [comment]
Sorry for not being able to respond earlier.. guess you got this!
