### ISSUE TITLE
Integration with Netatmo Wortstation

### ISSUE THREAD

**Issue by Sergbmw** [MTry/homebridge-smart-irrigation#8]
It would be nice to integrate with Netatmo Wortstation and take data on wind, temperature and rain locally from them

**Comment by MTry** [comment]
Sorry.. don't have access to Netatmo device.. although this could be an interesting option offering even greater precision - will have to give it a pass unless someone volunteers to help code this 🙂

**Comment by MTry** [comment]
Thanks - will surely take you up on your offer once I can allocate some more time to this feature development!🙂
